version: 2.1

orbs:
  node: circleci/node@5.1.0
  semantic-release: trustedshops-public/semantic-release@3.1.5
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: |
            npm run build
      - codecov/upload:
          file: junit.xml
  release:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - semantic-release/create-changelog-config-github
      - semantic-release/execute

workflows:
  main:
    jobs:
      - build:
          requires:
            - test
      - node/test:
          name: test
          run-command: test --ci --reporters=default --reporters=jest-junit
          pkg-manager: yarn
          test-results-path: junit.xml
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                # TOOD: Change to main to enable publish
                - main-enable
          context:
            - semantic-release
            - npm-registry
